project_id = "nadtoitgkukzbghtbohm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[analytics]
enabled = false
port = 54328

[vector]
enabled = true
port = 54329

[functions.listUsers]
verify_jwt = false

[functions.storage-stats]
verify_jwt = false

[functions.delete-expired-documents]
verify_jwt = false

[functions.process-document-queue]
verify_jwt = true

[functions.receive-n8n-response]
verify_jwt = false

[functions.close-month]
verify_jwt = true

[functions.get-document-url]
verify_jwt = false

[functions.align-document]
verify_jwt = true

[functions.reopen-month]
verify_jwt = false

[functions.check-close-month-status]
verify_jwt = true

[functions.get-signed-url]
verify_jwt = true

[functions.check-verification-status]
verify_jwt = true
